language: java
dist: xenial

before_install:
- mkdir lib
- git clone --depth 50 https://github.com/petercorke/toolbox-common-matlab lib/toolbox-common-matlab
- git clone --depth 50 https://github.com/petercorke/spatial-math lib/spatial-math

install: curl -sL https://storage.googleapis.com/matlabimagesus/public/install.sh | sudo -E bash

script:
- matlab -sd unit_test -batch "RunAllTests"

after_success:
- bash <(curl -s https://codecov.io/bash)
